deps: 
  - advancecomp
  - autoconf 
  - automake 
  - bison 
  - build-essential 
  - curl 
  - exuberant-ctags 
  - gifsicle
  - git-core
  - imagemagick
  - jpegoptim
  - libcurl4-openssl-dev #nginx/passenger requirement
  - libjpeg-progs
  - libmagickcore-dev
  - libmagickwand-dev
  - libmysqlclient-dev
  - libreadline6 
  - libreadline6-dev 
  - libreadline-dev
  - libssl-dev 
  - libncurses5-dev
  - libtool
  - libxml2-dev 
  - libxslt1-dev 
  - memcached
  - mysql-server
  - openssl 
  - optipng
  - pngcrush
  - python-mysqldb # for Ansible mysql module
  - unzip
  - zlib1g 
  - zlib1g-dev

mysqld:
  bind_address: 127.0.0.1
  key_buffer: 16M
  max_connection: 100
  utf8: true

memcached:
  memory: 64
  port: 11211
  user: root
  listen: 127.0.0.1
  max_connections: 1024

nginx:
  connections: 1024

rbenv_path: /home/$user/.rbenv #/usr/local/.rbenv
ruby_home: /home/$user/.rbenv/shims
rbenv_home: ${rbenv_path}/bin
path: PATH="${rbenv_path}/bin:${rbenv_path}/plugins/ruby-build/bin:/home/$user/.rbenv/shims:$PATH"
ruby_version: 2.0.0-p247 #1.9.3-p392
source: . ~/.profile
port: 3000
environment: production
passenger_root: ${rbenv_path}/versions/$ruby_version/lib/ruby/gems/2.0.0/gems/passenger-4.0.10
