development: 
  app_name: 
    short: _base
    long: base
  
  theme: default
  
  meta:
    title: title
    subtitle: subtitle
    
  perform_authentication: true
  send_email: false
  default_from_email: XXX  

  home:
    call: call
    subcall: subcall
    values:
      - lead: lead
        follow: follow
  
  socmedia:
    facebook:
      include_follow: false
      facebook_page: 
    twitter:
      include_follow: false
      twitter_page: 
  
  decisions:
    name: 
      short: option
      full: Option
  
  footer:
    has_custom_resources: true
    resources:
      - title: title
        items:
          - anchor: anchor
            link: link
            title: title
      
         
  
test: 
  default_to: development
  perform_authentication: true
  send_email: true


production:
  default_to: development
  perform_authentication: true
  send_email: true

